version: '3.8'

services:
  user-db:
    image: postgres:15-alpine
    container_name: user_db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - intellcap-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: .
    container_name: user_service
    ports:
      - "8092:8082"
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: intellcap_secret_key_2024_very_long_string
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user_db
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - intellcap-network

volumes:
  user_db_data:

networks:
  intellcap-network:
    driver: bridge